# Generated by Django 4.0.3 on 2022-11-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('salesAmount', models.FloatField()),
                ('salesShare', models.FloatField()),
                ('salesInten', models.FloatField()),
                ('salesChange', models.FloatField()),
                ('salesAcc', models.FloatField()),
                ('audiCnt', models.FloatField()),
                ('audiInten', models.FloatField()),
                ('audiChange', models.FloatField()),
                ('audiAcc', models.FloatField()),
                ('scrnCnt', models.FloatField()),
                ('showCnt', models.FloatField()),
                ('genres', models.TextField()),
                ('nation', models.CharField(max_length=10)),
                ('prodDate', models.CharField(max_length=8)),
                ('openDate', models.CharField(max_length=8)),
                ('companys', models.TextField()),
                ('actors', models.TextField()),
                ('directors', models.TextField()),
                ('poster', models.TextField()),
                ('link', models.TextField()),
                ('ratingAudi', models.FloatField()),
                ('ratingCritic', models.FloatField()),
                ('ratingNetizen', models.FloatField()),
                ('summaryContent', models.TextField()),
                ('summaryNote', models.TextField()),
                ('ratingNetizenM', models.FloatField()),
                ('ratingNetizenF', models.FloatField()),
                ('ratingNetizen10', models.FloatField()),
                ('ratingNetizen20', models.FloatField()),
                ('ratingNetizen30', models.FloatField()),
                ('ratingNetizen40', models.FloatField()),
                ('ratingNetizen50', models.FloatField()),
                ('ratingAudiM', models.FloatField()),
                ('ratingAudiF', models.FloatField()),
                ('ratingAudi10', models.FloatField()),
                ('ratingAudi20', models.FloatField()),
                ('ratingAudi30', models.FloatField()),
                ('ratingAudi40', models.FloatField()),
                ('ratingAudi50', models.FloatField()),
                ('ratingNetizenDir', models.PositiveSmallIntegerField()),
                ('ratingNetizenAct', models.PositiveSmallIntegerField()),
                ('ratingNetizenScn', models.PositiveSmallIntegerField()),
                ('ratingNetizenMis', models.PositiveSmallIntegerField()),
                ('ratingNetizenOst', models.PositiveSmallIntegerField()),
                ('ratingAudiDir', models.PositiveSmallIntegerField()),
                ('ratingAudiAct', models.PositiveSmallIntegerField()),
                ('ratingAudiScn', models.PositiveSmallIntegerField()),
                ('ratingAudiMis', models.PositiveSmallIntegerField()),
                ('ratingAudiOst', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=10)),
                ('mbti', models.CharField(max_length=4)),
                ('vote_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.movieinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MovieChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys.movieinfo')),
            ],
        ),
    ]
